### ISSUE TITLE
WEB - Alta de usuario: Rubros de la empresa

### ISSUE THREAD

**Issue by mpanero** [mpanero/wt#1]
Preguntas para confirmar:
1-De donde estamos sacando todas las actividades (Rubros) posibles para que seleccione el usuario
2-Donde se está almacenado la relación de las actividades seleccionadas (Rubros) con el usuario

**Comment by ruzcat** [comment]
1._ tabla t_type_activity
2._ campo ACTIVITY separado por (,)
