### ISSUE TITLE
WEB - Registro de empresa - Varios

### ISSUE THREAD

**Issue by mpanero** [mpanero/wt#4]
1-Validación de CUIT
Cambiar mensaje: "Cancelado!
Valor NO valido para campo CUIT"
Por 
"Por favor ingrese un número de CUIT válido"

2-Confirmación de registro
Cambiar: 
"Mensaje!
Su usuario se ha creado con éxito. La activación se realizará a la brevedad"
Por
"Mensaje!
"Usuario creado con éxito. 
La activación se su cuenta se realizará a la brevedad"

*Tener en cuenta los saltos de lienea

**Comment by ruzcat** [comment]
Corregido
